### ISSUE TITLE
adding the required plugin fails

### ISSUE THREAD

**Issue by jrlandau** [Collaborne/cordova-gallery-access#4]
The error message is: "Error: Failed to fetch plugin https://github.com/SuryaL/cordova-gallery-api.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect."

**Comment by ThomasNierengarten** [comment]
It's the same for me..
<img width="979" alt="capture d ecran 2017-10-26 a 20 13 37" src="https://user-images.githubusercontent.com/31687599/32069716-47bb1014-ba8a-11e7-8d8a-cdf4a691bb3f.png">

**Comment by ankon** [comment]
Thanks for the report.

I believe this is ultimately caused by the use of Cordova CLI 7.x, and I have file an issue (in our own fork of) cordova-gallery-api to resolve this: https://github.com/Collaborne/cordova-gallery-api/issues/1

The installation should succeed if you use the `--nofetch` flag for `cordova plugin add`; the README is updated to use this for now.
